//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BomberRepository
{
    public partial class Account
    {
        #region Primitive Properties
    
        public virtual int AccountId
        {
            get;
            set;
        }
    
        public virtual string Login
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual string AccountType
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Player Player
        {
            get { return _player; }
            set
            {
                if (!ReferenceEquals(_player, value))
                {
                    var previousValue = _player;
                    _player = value;
                    FixupPlayer(previousValue);
                }
            }
        }
        private Player _player;

        #endregion
        #region Association Fixup
    
        private void FixupPlayer(Player previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Account, this))
            {
                previousValue.Account = null;
            }
    
            if (Player != null)
            {
                Player.Account = this;
            }
        }

        #endregion
    }
}
