//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace BomberRepository
{
    public partial class BomberDbContext : ObjectContext
    {
        public const string ConnectionString = "name=BomberDbContext";
        public const string ContainerName = "BomberDbContext";
    
        #region Constructors
    
        public BomberDbContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public BomberDbContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public BomberDbContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Account> Accounts
        {
            get { return _accounts  ?? (_accounts = CreateObjectSet<Account>("Accounts")); }
        }
        private ObjectSet<Account> _accounts;
    
        public ObjectSet<Player> Players
        {
            get { return _players  ?? (_players = CreateObjectSet<Player>("Players")); }
        }
        private ObjectSet<Player> _players;
    
        public ObjectSet<Game> Games
        {
            get { return _games  ?? (_games = CreateObjectSet<Game>("Games")); }
        }
        private ObjectSet<Game> _games;
    
        public ObjectSet<Conversation> Conversations
        {
            get { return _conversations  ?? (_conversations = CreateObjectSet<Conversation>("Conversations")); }
        }
        private ObjectSet<Conversation> _conversations;

        #endregion
    }
}
